version: 2.1
orbs:
  node: circleci/node@3.0.0
workflows:
  matrix-tests:
    jobs:
      - node/test:
          version: 10.18.0
          override-ci-command: "npm install"
      - node/test:
          version: 12.14.0
          override-ci-command: "npm install"
